sakurassweets/sakurassweets-frontend

- src/components/Header/Header.tsx
> EAM-91 Remove subheader

- src/components/ProductCard/FavoriteBtn/FavoriteBtn.module.scss
- src/components/ProductCard/ProductCard.module.scss
- src/components/ProductCard/ProductCardHeader/ProductCardHeader.module.scss
- src/components/ProductCard/ProductDescription/ProductDescription.module.scss
- src/components/ProductCard/ProductImg/ProductImg.module.scss
- src/components/ProductCard/ProductPrice/CurrentPrice/CurrentPrice.module.scss
- src/components/ProductCard/ProductPrice/ProductPrice.module.scss
- src/components/ProductCard/ProductPrice/RealPrice/RealPrice.module.scss
- src/components/ProductCard/RatingBar/RatingBar.module.scss
- src/components/ProductCard/RatingBar/StarRating/StarImg/StarImg.module.scss
- src/components/ProductCard/RatingBar/StarRating/StarRating.module.scss
- src/components/ProductCard/RatingBar/StockCheck/StockCheck.module.scss
- src/components/ProductCard/SaleImg/SaleImg.module.scss
- src/pages/HomePage/HomePage.tsx
> Add prod card

- package-lock.json
- package.json
- src/index.scss
> Add normalize

- src/components/Header/MainHeader/MainHeader.module.scss
- src/components/Header/MainHeader/MainHeader.tsx
- src/components/UserRoutes.tsx
- src/pages/Catalog/Catalog.tsx
> EAM-93 Redirect to the catalog page

- src/components/HomePaige/AdvantagesList/AdvantagesList.tsx
This reverts commit cf1bd17b48d5116f192efdd78633fcd8e00634ec.
Implement:
This is a:
> Revert "Eam 90 (#29)"

- package-lock.json
- package.json
- src/components/Modal/AuthModal/AuthModalContent.tsx
- src/main.tsx
- src/redux/auth/operations.ts
- src/redux/auth/slice.ts
- src/redux/hook.ts
- src/redux/store.ts
Implement:
**EAM-85:**
**EAM-86:**
**EAM-87:**
**EAM-88:**
**EAE 89:**
This is a:
> Eam 86 integrate auth forms with service

- package-lock.json
- package.json
- src/components/Loader/Loader.module.scss
- src/components/Loader/Loader.tsx
- src/components/UserRoutes.tsx
Implement:
🍕 Feature - added Loader
> EAM-118 added Loader InfinitySpin

- src/components/Modal/Modal.tsx
Implement:
added Escape close for modal window
> EAM-124 added escape close

- src/components/Header/MainHeader/MainHeader.module.scss
- src/components/Header/MainHeader/MainHeader.tsx
> EAM-133 implement clear and submit on search input

- src/components/Header/MainHeader/MainHeader.module.scss
- src/components/Header/MainHeader/MainHeader.tsx
> Eam 133 add input clear submit

- src/components/Modal/AuthModal/AuthControls/LoginControl.tsx
- src/components/Modal/AuthModal/AuthControls/RegisterControl.tsx
- src/constants/index.tsx
- src/schemas/validators.ts
> EAM-130 adde const and updated files login and reg control

- src/components/Footer/Footer.tsx
> EAM-123 updated footer nav according to design

- src/components/Modal/AuthModal/AuthModalContent.tsx
- src/index.scss
- src/styles/toast.scss
> EAM-122 updated toastify styles

- src/components/Modal/AuthModal/AuthModalContent.tsx
- src/index.scss
- src/main.tsx
- src/styles/toast.scss
> Eam 122 frontend update toast styles

- src/components/Input/Input.module.scss
- src/components/Modal/AuthModal/AuthControls/LoginControl.tsx
- src/components/Modal/AuthModal/AuthModal.module.scss
- src/components/Modal/Modal.module.scss
Implement:
-  Fixed the display of all input fields on the page, including the header and modals.
-  Added a "Forgot Password?" link to the login form for user convenience.
-  Added a "pointer" cursor to all buttons and links where necessary.
This is a:
> Fixing the input fields display

- README.md
- src/components/Layout/Layout.tsx
Implement:
-  Added rules for git worflow
-  Added rules for compontents declaration
This is a:
> SAK-57 Added new rules to README

- src/components/Authorization/AuthorizationControls/LoginControl.tsx
- src/components/Authorization/AuthorizationControls/RegisterControl.tsx
- src/components/Authorization/AuthorizationModal.module.scss
- src/components/Authorization/AuthorizationModalContent.tsx
- src/components/Common/Modal/Modal.module.scss
- src/components/Common/Modal/Modal.tsx
- src/components/Layout/Footer/SocialList/Telegram.tsx
Implement:
-  Modal Style behaviour
- added animation for open and close modal
-  refactoring imports
This is a:
> fix: Fixed Modal Open behaviour

- src/components/Common/Toast/Toast.module.scss
- src/components/Common/Toast/ToastIcon.tsx
- src/main.tsx
- src/styles/helpers/toast.scss
- src/styles/helpers/vars.scss
Implement:
-  toast styles:
- added new icons and color styles
This is a:
> Sak 13 update toast styles

- src/components/Common/ProductCard/ProductCard.module.scss
- src/components/Common/ReviewCard/ReviewCard.tsx
- src/components/Common/Slider/Slider.module.scss
- src/components/Common/Slider/Slider.tsx
- src/pages/Home/Home.tsx
Implement:
- updated slider styles 
- add dots for all sliders
- add styles for dots
This is a:
> SAK-62 slider updated

- src/components/UserRoutes.tsx
- src/constants/routers.tsx
Implement:
-  Add constants:
- update the UserRoutes
This is a:
> [SAK-66] add constants to routers

- src/components/Common/ProductCard/ProductCard.module.scss
- src/components/Common/Slider/Slider.module.scss
- src/components/Common/Slider/Slider.tsx
- src/components/Home/Hero/Hero.module.scss
- src/components/Home/Hero/Hero.tsx
Implement:
-  Fix bug with button's text:
- Add constant to routing
This is a:
> [SAK-65] bug fix

- src/components/Common/ProductCard/ProductCard.module.scss
- src/components/Common/Slider/Slider.module.scss
- src/components/Common/Slider/Slider.tsx
Implement:
-  Slider refactoring:
This is a:
> SAK-62-slider-refactoring

- src/styles/helpers/vars.scss
Implement:
-  Add colors:
This is a:
> [SAK-69] Add colors to vars

- src/components/Common/Buttons/AddToCart/ButtonAddToCart.tsx
- src/components/Common/ProductCard/ProductCard.tsx
- src/components/Common/Toast/CloseButton.tsx
- src/components/Layout/Header/components/headerControl/HeaderControl.tsx
- src/main.tsx
Implement:
-  Refactor ButtonAddToCart:
- remove useEffect
-  Refactor ProductCard components:
- move Btn added to cart from the Link
This is a:
>  Refactor ButtonAddToCart and ProductCard components

- src/components/Authorization/AuthorizationModal.module.scss
- src/components/Authorization/authorizationModal.module.scss
- src/components/Common/Inputs/Input.module.scss
- src/components/Common/Inputs/input.module.scss
- src/styles/base/reset.scss
Implement:
-  Updated input styles
This is a:
> Refactor input styles to use transparent background color

- src/components/Authorization/AuthorizationModal.module.scss
- src/components/Authorization/AuthorizationModal.tsx
- src/components/Authorization/AuthorizationModalContent.tsx
- src/components/Authorization/authorizationModal.module.scss
- src/components/Cart/CartComponent.tsx
- src/components/Cart/components/index.ts
- src/components/Common/Inputs/Input.module.scss
- src/components/Common/Inputs/input.module.scss
- src/components/Common/Modal/components/modalImg/ModalImage.tsx
- src/components/Common/Modal/components/modalImg/modalImage.module.scss
- src/components/Common/Modal/index.ts
- src/components/Common/index.ts
- src/components/Layout/Header/Header.tsx
- src/components/Layout/Header/components/searchForm/searchForm.module.scss
- src/components/OrderSuccess/OrderSuccess.tsx
- src/components/OrderSuccess/orderSuccess.module.scss
Implement:
-  Created Order Success Modal:
-  Created Modal Image component
-  Updated AuthModal styles
This is a:
> SAK-87 created Order Success Modal
